#
# GMT 6.0.0 Defaults file
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 11.5p,Helvetica-Bold,black
FONT_LABEL                     = 13p,Helvetica-Bold,black
#
# MAP Parameters
#
MAP_FRAME_PEN                  = thin,black
MAP_TICK_LENGTH_PRIMARY        = 4p/2p
MAP_TICK_LENGTH_SECONDARY      = 1.5p/0.375p
MAP_TICK_PEN_PRIMARY           = thin,black
MAP_TICK_PEN_SECONDARY         = thin,black
#
# PostScript Parameters
#
PS_CHAR_ENCODING               = Standard+
